### ISSUE TITLE
Eats up all my ram

### ISSUE THREAD

**Issue by sils1297** [tav/asciinema2gif#20]
It just ate up something like 15GBs of ram/swap while trying to convert https://asciinema.org/a/3uftg7cenn3dgga0ji8w1xniu?speed=2 with `-s small` - anything I can do?

**Comment by vitorgalvao** [comment]
This tool consists of a shell script that calls three other tools (`phnatomjs`, `gifsicle`, `imagemagick`). At which point is the huge RAM consumption? Downloading, converting the download to a gif, or both?

**Comment by sils1297** [comment]
Converting, I should have provided the error message, will do when I get to
a pc.

**Comment by vitorgalvao** [comment]
The conversion process is completely offset to `imagemagick` and `gifsicle`, so there’s likely nothing `asciinena2gif` can do in that case. If it’s a bug, it’ll be with one of those tools. Perhaps you’re using old versions. If not, you’ll have to report the bug in their respective bug trackers.

There’s also the chance it’s expected behaviour, and the images in that asciicast or the used command flags are simply too much to handle in that case.

Try editing the exact command (near the bottom of the script) to only use one tool or the other (right now it’s a pipe) and play with the option flags to try and find the culprit.

**Comment by sils1297** [comment]
Hi, I have no time to investigate this issue further.

**Comment by techtonik** [comment]
@vitorgalvao what is the role of `imagemagick` and `gifsicle` in the process? One tool should be enough, no?

**Comment by vitorgalvao** [comment]
@wong2 [This issue can be closed for now](https://github.com/tav/asciinema2gif/issues/20#issuecomment-218405010). Thank you for reporting back, @sils1297.

@techtonik See https://github.com/tav/asciinema2gif/issues/10.
